/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
typedef volatile uint32_t vuint32_t;

// address of the peripherals
#define RCC_base		        0x40021000
#define GPIOA_base 			0x40010800
#define RCC_APB2ENR                     *(vuint32_t*)(RCC_base + 0x18)
#define GPIOA_CRH 			*(vuint32_t*)(GPIOA_base + 0x04)
#define GPIOA_ODR 			*(vuint32_t*)(GPIOA_base + 0x0C)


typedef union{
	vuint32_t all_fields;
	struct{
		vuint32_t  reserved:13;
		vuint32_t  P_13:1;
	}Pins;
}G_ODR_t;

volatile G_ODR_t* ODR = (volatile G_ODR_t*)(GPIOA_base + 0x0C);

int main(void)
{
	RCC_APB2ENR |= 1<<2 ;
	GPIOA_CRH &= 0XFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		ODR->Pins.P_13 = 1;
		for(int i=0; i<5000; i++); //delay
		ODR->Pins.P_13 = 0;
		for(int i=0; i<5000; i++); //delay

	}
}
